stages:
  - validate_cfn
  - stage_deploy_dev

stage_validate_cfn:
  stage: validate_cfn
  script:
    - pip install awscli
    - pip install cfn-lint
    - cfn-lint -i="W1020,W2001" components/*.yaml
  except:
    - master
    - development
    - sandbox
  tags:
    - Python

stage_deploy_dev:
  stage: stage_deploy_dev
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
#    - COMPONENT=moodle34-security-groups make update-stack
    - COMPONENT=sample-app-ecr make update-stack
    - ECRURL=$(aws ssm get-parameter --name "/cloudformation/applications/dev/ecr/ECR/sample-app" --output text --query Parameter.Value)

#    # Yeah this looks bad, but it is better then it would be otherwise.
    #- if [ ! -d "$HOME/packer" ]; then mkdir ~/packer; pushd ~/packer; wget https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip; unzip ./packer_1.3.4_linux_amd64.zip; popd; fi 
    - ~/packer/packer build -var 'docker-repo=${ECRURL}' -var 'playbook_dir=docker-image/ansible-local' -var 'build_version=${CI_MERGE_REQUEST_ID}' docker-image/packer/sample-lamp.json
  only: 
    - development
  tags:
    - awscliDocker
