stages:
  - validate_cfn
  - stage_deploy_dev
  - stage_install_packer
  - stage_build_docker

stage_validate_cfn:
  stage: validate_cfn
  script:
    - pip install awscli
    - pip install cfn-lint
    - cfn-lint -i="W1020,W2001" components/*.yaml
  except:
    - master
    - development
    - sandbox
  tags:
    - Python

stage_install_packer:
  variables:
   CI_DEBUG_TRACE: "true"
  stage: stage_install_packer
  script:
    #   Yeah this looks bad, but it is better then it would be otherwise. Install packer if not installed
    - if [ ! -d "$HOME/packer" ]; then mkdir ~/packer; pushd ~/packer; wget https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip; unzip ./packer_1.3.4_linux_amd64.zip; popd; fi     
  only:
    - development
  tags:
    - awscliDocker

stage_deploy_dev:
  stage: stage_deploy_dev
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
#    - COMPONENT=moodle34-security-groups make update-stack
    - COMPONENT=sample-app-security-groups make update-stack
    - COMPONENT=sample-app-rds make update-stack
    - COMPONENT=sample-app-alb make update-stack
    - COMPONENT=sample-app-ecr make update-stack
  only: 
    - development
  tags:
    - awscliDocker

stage_build_docker:
  stage: stage_build_docker
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
    # Store the ecr location in a file so we can pull it out in the next step
    - aws ssm get-parameter --name "/cloudformation/applications/dev/ecr/sample-app" --output text --query Parameter.Value > ~/ecrRegistry
    # Build the image, 
    - ECRURL=$(cat ~/ecrRegistry) && ~/packer/packer build -var "docker-repo=$ECRURL" -var "playbook_dir=docker-image/ansible-local" -var "build_version=$CI_MERGE_REQUEST_ID" -var "ssmdbparam=/cloudformation/applications/dev/sample-app-rds/secret/name"docker-image/packer/sample-lamp.json
  when: manual