stages:
  - validate_cfn
  - stage_deploy_dev
  - stage_build_docker
  - update_service_ecs

stage_validate_cfn:
  stage: validate_cfn
  script:
    - pip install awscli
    - pip install cfn-lint
    - cfn-lint -i="W1020,W2001" components/*.yaml
  except:
    - master
    - development
    - sandbox
  tags:
    - Python

stage_deploy_dev:
  stage: stage_deploy_dev
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
    - COMPONENT=sample-app-security-groups make update-stack
    - COMPONENT=sample-app-rds make update-stack
    - COMPONENT=sample-app-alb make update-stack
    - COMPONENT=sample-app-ecr make update-stack
    - COMPONENT=sample-app-service make update-stack
  only: 
    - development
  tags:
    - awscliDocker

stage_build_docker:
  stage: stage_build_docker
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
    - chmod 700 ./make_scripts/make_image.sh
    - ./make_scripts/make_image.sh sample-app
  only:
    - development
  when: manual
  tags:
    - awscliDocker

update_service_ecs:
  stage: update_service_ecs
  before_script:
    - export AWS_ACCESS_KEY_ID=$DEV_AccessKey
    - export AWS_SECRET_ACCESS_KEY=$DEV_SecretKey
    - export AWS_DEFAULT_REGION=us-east-1
    - export PROJECT=applications
    - export ENV=dev
    - export PROFILE=dev
  script:
    - chmod 700 ./make_scripts/update_service.sh
    - ./make_scripts/update_service.sh sample-app
  only:
    - development
  when: manual
  tags:
    - awscliDocker