Description: >
  This is an example of a long running ECS service that serves a JSON API of products.

Parameters:
  ProjectName:
    Type: String
    Description: A project to associate with resources in the template (e.g. 'InitiativeX')

  EnvironmentName:
    Type: String
    Description: A description to identify environment (e.g. dev, prod)

  ComponentName:
    Type: String
    Description: A description to identify component in the project; e.g. networking

  SsmLookupVpcId:
    Description: Choose which VPC this ECS cluster should be deployed to
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>

  SsmLookupClusterName:
    Description: The ECS Cluster ID that this service should run on
    Type: AWS::SSM::Parameter::Value<String>

  SsmLookupLoadBalancerListenerArn:
    Description: The Application Load Balancer listener to register with
    Type: AWS::SSM::Parameter::Value<String>

  SsmLookupApplicationAutoScalingRoleArn:
    Description: The Application Autoscaling role to use
    Type: AWS::SSM::Parameter::Value<String>

  TaskName:
    Description: Name for the task/service
    Type: String

  Path:
    Description: The path to register with the Application Load Balancer
    Type: String

  HealthCheckPath:
    Description: The health check path for the service
    Type: String

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number

  ContainerPort:
    Description: Port that the container listens on
    Type: Number


Resources:
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !Ref SsmLookupClusterName
      # Role: Uses AWSServiceRoleForECS by default.
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      SchedulingStrategy: REPLICA
      LoadBalancers:
        - ContainerName: !Ref TaskName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${TaskName}-service
      TaskRoleArn: !GetAtt [TaskRole, Arn]
      NetworkMode: bridge
      ContainerDefinitions:
        - Name: !Ref TaskName
          Essential: true
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}/${EnvironmentName}/ecr/${TaskName}:latest"
          Memory: 128
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      # ManagedPolicyArns:
      #   - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${ProjectName}/${EnvironmentName}/${ComponentName}/${TaskName}"
      RetentionInDays: 365

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref SsmLookupVpcId
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref SsmLookupLoadBalancerListenerArn
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref Path
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Join ["/", [service, !Ref "SsmLookupClusterName", !GetAtt [Service, Name]]]
      RoleARN: !Ref SsmLookupApplicationAutoScalingRoleArn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ScalingPolicy:
    Type : AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: service-scaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        DisableScaleIn: False
        ScaleInCooldown: 300
        ScaleOutCooldown: 300
        TargetValue: 60
