AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template deploys an Application Load Balancer that exposes our various ECS services.

Parameters:
  ProjectName:
    Type: String
    Description: A project to associate with resources in the template (e.g. 'InitiativeX')

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  ComponentName:
    Type: String
    Description: A description to identify component in the project; e.g. networking

  SsmLookupVpcId:
    Description: Choose which VPC this ECS cluster should be deployed to
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>

  SsmLookupSubnetIds:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>

  SsmLookupLoadBalancerSecurityGroup:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>


Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name:
        "Fn::Sub":
          "${ProjectName}-${EnvironmentName}-${ComponentName}"
      Subnets: !Ref SsmLookupSubnetIds
      SecurityGroups:
        - !Ref SsmLookupLoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value:
            "Fn::Sub":
              "${ProjectName}-${EnvironmentName}-${ComponentName}"

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  # Unused - necessary for a listener, but create one per service instead.
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref SsmLookupVpcId
      Port: 80
      Protocol: HTTP


  LoadBalancerHttpListenerParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name:
        "Fn::Sub":
          "/cloudformation/${ProjectName}/${EnvironmentName}/${ComponentName}/http-listener/arn"
      Type: "String"
      Value: { Ref: LoadBalancerListener }

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListener
